apiVersion: v1
description: A Helm chart for Kubernetes (alfresco-process-variables-connector-service)
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: alfresco-process-variables-connector-service
version: 0.1.0
