apiVersion: v1
description: A Helm chart for Kubernetes (aps-cloud-connector-email)
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: alfresco-process-lambda-connector-service
version: 0.0.1
